#!/bin/bash

if [[ $# -lt 1 ]] || [[ ! -e "$1" ]]; then
	echo "usage: $(basename "$0") AN.hfstol [TEXT...]" >&2
	exit 1
fi

t="$1"
shift

cat "$@" \
  | sed 's@[][/<>]@\\\0@g' \
  | hfst-proc "$t" 2>/dev/null \
  | grep -o '\^[^$]*\$' \
  | grep '\*' \
  | sort \
  | uniq -c \
  | sort -n
